### ISSUE TITLE
制定一个 Resources Repo 规范，并将 Resources 转移到单独的仓库

### ISSUE THREAD

**Issue by AzurIce** [AzurIce/azur-arknights-helper#16]
考虑到 Aah 正向通用框架方向发展，对于不同应用任务其 Resources 应当分隔开，因此需要确定一个 Resources Repo 规范，在初始化时能够直接通过 Repo 链接加载 Resources。

目前，一个 Resources Repo 定义如下：

```
/resources-repo
    /tasks
    /templates
    manifest.toml
```

`manifest.toml` 中内容如下：

```toml
platform = "android" # android 或 pc
last_updated = "2025-02-16T18:23:24.1015918+08:00" # 资源上次更新时间，用于资源更新时检查
```
